[package]
name = "bonsai-starter-methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
ethabi = { version = "18.0", default-features = false }
risc0-zkvm = { version = "=0.15.0", default-features = false }

[profile.release]
lto = true
opt-level = 3
