[package]
name = "bonsai-starter-methods-guest"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fibonacci"
path = "src/bin/fibonacci.rs"

[dependencies]
ethabi = { version = "18.0", default-features = false }
risc0-zkvm = { git = "https://github.com/risc0/risc0", branch = "release-0.15", default-features = false }

[profile.release]
lto = true
opt-level = 3

[workspace]
