[package]
name = "bonsai-starter-methods"
version = "0.1.0"
edition = "2021"

[package.metadata.risc0]
methods = ["guest"]

[build-dependencies]
risc0-build = "=0.15.0"

[dependencies]
bytemuck = "1.13.1"
clap = { version = "4.2.7", features = ["derive"] }
hex = "0.4.3"
risc0-zkvm = "=0.15.0"
