[package]
name = "bonsai-starter-methods"
version = "0.1.0"
edition = "2021"

[package.metadata.risc0]
methods = ["guest"]

[build-dependencies]
risc0-build = { git = "https://github.com/risc0/risc0", rev = "ecc0cc0c68b957a2988150dd8cf83524c4fd6f58", features = ["guest-list"] }

[dependencies]
bytemuck = "1.13.1"
clap = { version = "4.2.7", features = ["derive"] }
hex = "0.4.3"
risc0-build = { git = "https://github.com/risc0/risc0", rev = "ecc0cc0c68b957a2988150dd8cf83524c4fd6f58", features = ["guest-list"] }
risc0-zkvm = { git = "https://github.com/risc0/risc0", rev = "ecc0cc0c68b957a2988150dd8cf83524c4fd6f58" }
