[package]
name = "bonsai-starter-methods"
version = "0.1.0"
edition = "2021"

[package.metadata.risc0]
methods = ["guest"]

[build-dependencies]
risc0-build = { git = "https://github.com/risc0/risc0", rev = "b69ff7ac5dd7c341430aab1abddf671cc362a3ca", features = ["guest-list"] }

[dependencies]
risc0-build = { git = "https://github.com/risc0/risc0", rev = "b69ff7ac5dd7c341430aab1abddf671cc362a3ca", features = ["guest-list"] }
risc0-zkvm = { git = "https://github.com/risc0/risc0", rev = "b69ff7ac5dd7c341430aab1abddf671cc362a3ca" }
