[package]
name = "bonsai-starter-methods"
version = "0.1.0"
edition = "2021"

[package.metadata.risc0]
methods = ["guest"]

[build-dependencies]
risc0-build = { git = "https://github.com/risc0/risc0", rev = "ab3144a3161f4a3e7600421c6c24c4bba2ddeaa0", features = ["guest-list"] }

[dependencies]
bonsai-sdk = { git = "ssh://git@github.com/risc0/bpn.git", rev = "cac7a5b6727d0d931375972186cf6683460489fe" }
bytemuck = "1.13.1"
clap = { version = "4.2.7", features = ["derive"] }
hex = "0.4.3"
risc0-build = { git = "https://github.com/risc0/risc0", rev = "ab3144a3161f4a3e7600421c6c24c4bba2ddeaa0", features = ["guest-list"] }
risc0-zkvm = { git = "https://github.com/risc0/risc0", rev = "ab3144a3161f4a3e7600421c6c24c4bba2ddeaa0" }
tokio = { version = "1.0", features = ["full"] }

[patch.crates-io]
radium = { git = "https://github.com/bitvecto-rs/radium", rev = "723bed5abd75994ee4b7221b8b12c9f4e77ce408" }
