[package]
name = "bonsai-starter-methods"
version = "0.1.0"
edition = "2021"

[package.metadata.risc0]
methods = ["guest"]

[build-dependencies]
risc0-build = { git = "https://github.com/risc0/risc0", rev = "6f5b3497a611aad8d3a5db7e03c5e2adf02a26db", features = ["guest-list"] }

[dependencies]
risc0-build = { git = "https://github.com/risc0/risc0", rev = "6f5b3497a611aad8d3a5db7e03c5e2adf02a26db", features = ["guest-list"] }
risc0-zkvm = { git = "https://github.com/risc0/risc0", rev = "6f5b3497a611aad8d3a5db7e03c5e2adf02a26db" }
