[package]
name = "bonsai-starter-methods"
version = "0.1.0"
edition = "2021"

[package.metadata.risc0]
methods = ["guest"]

[build-dependencies]
risc0-build = { git = "https://github.com/risc0/risc0", rev = "d6f3ac8264233abe49f5383dc6e6df8812696ec2", features = ["guest-list"] }

[dependencies]
bonsai-client = { git = "ssh://git@github.com/risc0/bpn.git", rev = "8ff66e793487ac44e533a5096709017625b12dca" }
bonsai-common-rest = { git = "ssh://git@github.com/risc0/bpn.git", rev = "8ff66e793487ac44e533a5096709017625b12dca" }
bytemuck = "1.13.1"
clap = { version = "4.2.7", features = ["derive"] }
hex = "0.4.3"
risc0-build = { git = "https://github.com/risc0/risc0", rev = "d6f3ac8264233abe49f5383dc6e6df8812696ec2", features = ["guest-list"] }
risc0-zkvm = { git = "https://github.com/risc0/risc0", rev = "d6f3ac8264233abe49f5383dc6e6df8812696ec2" }
tokio = { version = "1.0", features = ["full"] }

[patch.crates-io]
radium = { git = "https://github.com/bitvecto-rs/radium", rev = "723bed5abd75994ee4b7221b8b12c9f4e77ce408" }
