[package]
name = "bonsai-starter-methods"
version = "0.1.0"
edition = "2021"

[package.metadata.risc0]
methods = ["guest"]

[build-dependencies]
risc0-build = { git = "https://github.com/risc0/risc0", rev = "b35e1faa37fb4b60cf8dd849cf46b14d1713c881", features = ["guest-list"] }

[dependencies]
risc0-build = { git = "https://github.com/risc0/risc0", rev = "b35e1faa37fb4b60cf8dd849cf46b14d1713c881", features = ["guest-list"] }
risc0-zkvm = { git = "https://github.com/risc0/risc0", rev = "b35e1faa37fb4b60cf8dd849cf46b14d1713c881" }
