name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  cargo:
    name: cargo lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: install rust
        uses: risc0/risc0/.github/actions/rustup@42266f0b6bd28de208b7c47b50dd4bcf241f76ce

      - name: install cargo-sort
        uses: risc0/cargo-install@v1
        with:
          crate: cargo-sort
          version: "^1.0.9"

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install solhint
        run: npm install -g solhint && solhint --version

      - name: lint solidity code
        run: solhint 'contracts/**/*.sol' 'lib/bonsai-lib-sol/src/**/*.sol'

      - name: lint rust code
        run: cargo fmt --all -- --check

      - name: lint cargo files
        run: cargo sort --workspace --check
